# Generated by Django 4.2.6 on 2023-10-16 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('P', 'Limpeza Profunda'), ('S', 'Limpeza Simples')], max_length=2)),
                ('preco', models.FloatField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Solicitado'), ('P', 'Pendente'), ('R', 'Realizado'), ('C', 'Cancelado')], max_length=2)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('D', 'Dinheiro em Espécie'), ('P', 'PIX'), ('C', 'Cartão de Crédito')], max_length=2, null=True)),
                ('dar_desconto', models.BooleanField(blank=True, default=False)),
                ('valor_desconto', models.FloatField(blank=True, null=True)),
                ('valor_pago', models.FloatField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('data_limpeza', models.DateTimeField(blank=True, null=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitacoes_atendente', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitacoes_cliente', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servicos.tiposservicos')),
            ],
        ),
    ]
