# Generated by Django 4.2.6 on 2023-10-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_solicitacaoservico_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposservicos',
            name='tipo',
        ),
    ]
